=begin
#Catalogs

#This API allows you to manage your catalogs

OpenAPI spec version: 2.0
Contact: support@beezup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SwaggerClient
  class BeezUPCommonColumnDataType
    
    STRING = "String".freeze
    URL = "Url".freeze
    TEXT = "Text".freeze
    DECIMAL = "Decimal".freeze
    DATE_TIME = "DateTime".freeze
    INT = "Int".freeze
    SPECIAL_INT = "SpecialInt".freeze
    IN_STOCK = "InStock".freeze
    UNKNOWN = "Unknown".freeze
    IMAGE_URL = "ImageUrl".freeze
  end

end
