=begin
#BeezUP API

#This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP

OpenAPI spec version: 2.0
Contact: support@beezup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ImportationProcessApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ImportationProcessApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ImportationProcessApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ImportationProcessApi' do
    it 'should create an instact of ImportationProcessApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ImportationProcessApi)
    end
  end

  # unit tests for importation_cancel
  # Cancel importation
  # 
  # @param store_id Your store identifier
  # @param execution_id The execution identifier of you catalog importation
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'importation_cancel test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for importation_commit
  # Commit Importation
  # 
  # @param store_id Your store identifier
  # @param execution_id The execution identifier of you catalog importation
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'importation_commit test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for importation_commit_columns
  # Commit columns
  # 
  # @param store_id Your store identifier
  # @param execution_id The execution identifier of you catalog importation
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'importation_commit_columns test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for importation_configure_remaining_catalog_columns
  # Configure remaining catalog columns
  # This operation should be used after you have mapped the required BeezUP Columns
  # @param store_id Your store identifier
  # @param execution_id The execution identifier of you catalog importation
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'importation_configure_remaining_catalog_columns test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for importation_get_importation_monitoring
  # Get the importation status
  # 
  # @param store_id Your store identifier
  # @param execution_id The execution identifier of you catalog importation
  # @param [Hash] opts the optional parameters
  # @return [ImportationMonitoring]
  describe 'importation_get_importation_monitoring test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for importation_get_reportings
  # Get the latest catalog importation reporting
  # 
  # @param store_id Your store identifier
  # @param [Hash] opts the optional parameters
  # @return [Array<ImportationReporting>]
  describe 'importation_get_reportings test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for importation_start_manual_update
  # Start Manual Import
  # 
  # @param store_id Your store identifier
  # @param request 
  # @param [Hash] opts the optional parameters
  # @return [Array<BeezUPCommonLink2>]
  describe 'importation_start_manual_update test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for importation_technical_progression
  # Get technical progression
  # 
  # @param store_id Your store identifier
  # @param execution_id The execution identifier of you catalog importation
  # @param [Hash] opts the optional parameters
  # @return [ImportationTechnicalProgression]
  describe 'importation_technical_progression test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
