=begin
#Public - Security

#This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 

OpenAPI spec version: 2.0
Contact: support@beezup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::MarketplacesChannelCatalogsPublicationsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MarketplacesChannelCatalogsPublicationsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::MarketplacesChannelCatalogsPublicationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MarketplacesChannelCatalogsPublicationsApi' do
    it 'should create an instact of MarketplacesChannelCatalogsPublicationsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::MarketplacesChannelCatalogsPublicationsApi)
    end
  end

  # unit tests for get_publications
  # Fetch the publication history for an account, sorted by descending start date
  # 
  # @param marketplace_technical_code Marketplace Technical Code to query (required)
  # @param account_id Account Id to query (required)
  # @param [Hash] opts the optional parameters
  # @option opts [String] :channel_catalog_id Channel Catalog Id by which to filter (optional)
  # @option opts [Integer] :count Amount of entries to fetch (optional, default set to 10)
  # @option opts [Array<String>] :publication_types Publication types by which to filter (optional)
  # @return [AccountPublications]
  describe 'get_publications test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
