=begin
#Public - Security

#This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 

OpenAPI spec version: 2.0
Contact: support@beezup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::MarketplacesOrdersListApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MarketplacesOrdersListApi' do
  before do
    # run before each test
    @instance = SwaggerClient::MarketplacesOrdersListApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MarketplacesOrdersListApi' do
    it 'should create an instact of MarketplacesOrdersListApi' do
      expect(@instance).to be_instance_of(SwaggerClient::MarketplacesOrdersListApi)
    end
  end

  # unit tests for get_order_list_full
  # Get a paginated list of all Orders with all Order and Order Item(s) properties
  # The purpose of this operation is to reduce the amount of request to the API.\\ \\ Previous implmentation of this feature only returned a partial (light) version of the Orders. The purpose of this API is to reduce the number of incoming requests by returning the complete (full) Order and Order Item(s) properties. 
  # @param accept_encoding Allows the client to indicate wether it accepts a compressed encoding to reduce traffic size
  # @param request 
  # @param [Hash] opts the optional parameters
  # @return [OrderListFull]
  describe 'get_order_list_full test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_order_list_light
  # Get a paginated list of all Orders without details
  # 
  # @param request 
  # @param [Hash] opts the optional parameters
  # @return [OrderListLight]
  describe 'get_order_list_light test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
