=begin
#BeezUP API

#This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP

OpenAPI spec version: 2.0
Contact: support@beezup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AlertsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AlertsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AlertsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AlertsApi' do
    it 'should create an instact of AlertsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AlertsApi)
    end
  end

  # unit tests for get_store_alerts
  # Get store&#39;s alerts
  # 
  # @param store_id Your store identifier
  # @param [Hash] opts the optional parameters
  # @return [StoreAlerts]
  describe 'get_store_alerts test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for save_store_alert
  # Save store alert
  # 
  # @param store_id Your store identifier
  # @param alert_id 
  # @param request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'save_store_alert test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
