=begin
#Public - Security

#This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 

OpenAPI spec version: 2.0
Contact: support@beezup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SwaggerClient
  class BeezUPCommonParameterType
    
    STRING = "string".freeze
    INTEGER = "integer".freeze
    NUMBER = "number".freeze
    BOOLEAN = "boolean".freeze
    OBJECT = "object".freeze
    ARRAY = "array".freeze
    DATE = "date".freeze
    DATE_TIME = "date-time".freeze
  end

end
