=begin
#BeezUP API

#This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP

OpenAPI spec version: 2.0
Contact: support@beezup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SwaggerClient
  class OrderExportationReportingProcessingStatus
    
    NONE = "None".freeze
    IN_PROGRESS = "InProgress".freeze
    DONE = "Done".freeze
    FAILED = "Failed".freeze
    ALREADY_IN_PROGRESS = "AlreadyInProgress".freeze
    ABORTED = "Aborted".freeze
    SUSPENDED = "Suspended".freeze
  end

end
