=begin
#BeezUP API

#This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP

OpenAPI spec version: 2.0
Contact: support@beezup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SwaggerClient
  class PublicationType
    
    PUBLISH_PRODUCTS = "PublishProducts".freeze
    PUBLISH_OFFERS = "PublishOffers".freeze
    UNPUBLISH = "Unpublish".freeze
  end

end
