=begin
#BeezUP API

#This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP

OpenAPI spec version: 2.0
Contact: support@beezup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SwaggerClient
  class RuleExecutionReportingErrorType
    
    CHANNEL_NOT_PRESENT = "ChannelNotPresent".freeze
    STORE_IS_IN_SYSTEM_BLOCK_STATE = "StoreIsInSystemBlockState".freeze
  end

end
