=begin
#BeezUP API

#This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP

OpenAPI spec version: 2.0
Contact: support@beezup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SwaggerClient
  class Type
    
    STRING = "string".freeze
    INTEGER = "integer".freeze
    BOOLEAN = "boolean".freeze
    NUMBER = "number".freeze
  end

end
