=begin
#Marketplaces - Channel catalogs

#This API allows you to manage your channel catalogs\\' marketplace settings and fetch your account\\'s catalog publication history

OpenAPI spec version: 2.0
Contact: support@beezup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SwaggerClient
  class BeezUPCommonHttpMethod
    
    GET = "GET".freeze
    POST = "POST".freeze
    PATCH = "PATCH".freeze
    DELETE = "DELETE".freeze
    PUT = "PUT".freeze
    HEAD = "HEAD".freeze
  end

end
