=begin
#Customer

#This API will gives you the ability to : - manage your account - manage your stores - shares your stores with your friends - manage your contracts - access to your invoices 

OpenAPI spec version: 2.0
Contact: support@beezup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::RightsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RightsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::RightsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RightsApi' do
    it 'should create an instact of RightsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::RightsApi)
    end
  end

  # unit tests for get_rights
  # Get store&#39;s rights
  # 
  # @param store_id Your store identifier
  # @param functionality_code_list The functionality code list you want to check
  # @param [Hash] opts the optional parameters
  # @return [Array<FunctionalityRightInfo>]
  describe 'get_rights test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
