=begin
#Catalogs

#This API allows you to manage your catalogs

OpenAPI spec version: 2.0
Contact: support@beezup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SwaggerClient
  class CompareOptions
    
    NONE = "None".freeze
    IGNORE_CASE = "IgnoreCase".freeze
    IGNORE_NON_SPACE = "IgnoreNonSpace".freeze
    IGNORE_SYMBOLS = "IgnoreSymbols".freeze
    ORDINAL_IGNORE_CASE = "OrdinalIgnoreCase".freeze
    STRING_SORT = "StringSort".freeze
    ORDINAL = "Ordinal".freeze
  end

end
