=begin
#Marketplaces - Channel catalogs

#This API allows you to manage your channel catalogs\\' marketplace settings and fetch your account\\'s catalog publication history

OpenAPI spec version: 2.0
Contact: support@beezup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::MarketplacesChannelCatalogsGlobalApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MarketplacesChannelCatalogsGlobalApi' do
  before do
    # run before each test
    @instance = SwaggerClient::MarketplacesChannelCatalogsGlobalApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MarketplacesChannelCatalogsGlobalApi' do
    it 'should create an instact of MarketplacesChannelCatalogsGlobalApi' do
      expect(@instance).to be_instance_of(SwaggerClient::MarketplacesChannelCatalogsGlobalApi)
    end
  end

  # unit tests for get_marketplace_account_stores
  # Get  you marketplace channel catalog list
  # 
  # @param [Hash] opts the optional parameters
  # @return [MarketplaceChannelCatalogList]
  describe 'get_marketplace_account_stores test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
