=begin
#Catalogs

#This API allows you to manage your catalogs

OpenAPI spec version: 2.0
Contact: support@beezup.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::StartManualImportRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StartManualImportRequest' do
  before do
    # run before each test
    @instance = SwaggerClient::StartManualImportRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StartManualImportRequest' do
    it 'should create an instact of StartManualImportRequest' do
      expect(@instance).to be_instance_of(SwaggerClient::StartManualImportRequest)
    end
  end
  describe 'test attribute "input"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "duplicate_product_sku_configuration"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

